#!/bin/bash

distro_name=`lsb_release -is | tr '[:upper:]' '[:lower:]'`

case $distro_name in
"neon")
  supported=true
  distro_name="ubuntu"
  ;;
"ubuntu")
  supported=true
  ;;
"debian")
  supported=true
  ;;
*)
  supported=false
esac

if [ $supported = true ]; then

  apt update

  apt install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common

  curl -fsSL "https://download.docker.com/linux/$distro_name/gpg" | apt-key add -

  add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/$distro_name \
    $(lsb_release -cs) \
    stable"

  apt update

  apt install docker-ce

  curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  chmod +x /usr/local/bin/docker-compose

  chmod a+rwx /var/run/docker.sock # TODO

else
  echo "unsupported distro"
fi
