#!/bin/bash

if ! which docker-compose > /dev/null; then
  echo "install docker"
  sudo ./docker/install
fi

echo "
USER_UID=$(id -u)
USER_GID=$(id -g)
" > .env

cmd=$@

if [[ $@ =~ [[:space:]]ruby/([^/$]+) ]]; then
  module=${BASH_REMATCH[1]}
  workdir="ruby/$module/"
  cmd=${@//$workdir/} # remove workdir from @
  cmd=${@//ruby\/$module/} # eg. rspec ruby/hyper-model => rspec
fi

docker-compose run -w "/app/$workdir" test bundle exec $cmd
